Repository zipdabang/android, pull requests merged in 2023-09, with the labels that each got.

#72 💄 [FEAT] MyNavgraph Complete(except FriendListScreen) and MyScreen UI
  app/build.gradle.kts
  app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/AuthNavGraph.kt
  app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/MyNavGraph.kt
  app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/Screen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/FriendListScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/LikeScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/MyScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/MyrecipeScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/ScrapScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/ShoppingScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/sign_up/data/remote/InfoResponse.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/sign_up/ui/RegisterPreferencesScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/sign_up/ui/RegisterUserAddressScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/sign_up/ui/TermsScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/sign_up/ui/viewmodel/AuthSharedViewModel.kt
  app/src/main/java/com/zipdabang/zipdabang_android/ui/component/AppBar.kt
  app/src/main/java/com/zipdabang/zipdabang_android/ui/component/CircleImage.kt
  app/src/main/java/com/zipdabang/zipdabang_android/ui/component/Drawer.kt
  app/src/main/java/com/zipdabang/zipdabang_android/ui/component/IconAndText.kt
  app/src/main/res/drawable/ic_my_bookmark.xml
  app/src/main/res/drawable/ic_my_favorite.xml
  app/src/main/res/drawable/ic_my_shopping_cart.xml
  app/src/main/res/values/strings.xml
Labels: :lipstick: styling

#80 :alien: [REFACTOR] Recipe Category API Change 반영
  app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/RecipeNavGraph.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/data/RecipeApi.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipeScreen.kt
Labels: :recycle: refactor

#82 :sparkles: [FEAT] Temp Sign up Business Logic Implementation
  app/src/main/java/com/zipdabang/zipdabang_android/core/AppModule.kt
  app/src/main/java/com/zipdabang/zipdabang_android/core/Paging3Database.kt
  app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/AuthNavGraph.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/use_case/GetRecipeDetailUseCase.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListContent.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/login/data/AuthApi.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/login/data/AuthRepositoryImpl.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/login/data/member/AuthBody.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/login/data/member/AuthDto.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/login/data/member/AuthTokenDto.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/login/data/temp/TempLoginDto.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/login/data/temp/TempTokenDto.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/login/domain/Auth.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/login/domain/AuthRepository.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/login/mapper/AuthMapper.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/login/ui/LoginScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/login/ui/LoginViewModel.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/login/ui/TempLoginState.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/login/use_case/GetAuthResultUseCase.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/login/use_case/GetTempLoginResultUseCase.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/main/MainActivity.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/data/RecipeApi.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/data/banner/RecipeBannerRepositoryImpl.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/data/common/RecipeItem.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/domain/RecipeBannerRepository.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipeMenuScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipePreviewByOwner.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/viewmodel/RecipeMainViewModel.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/GetRecipeBannerUseCase.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/GetRecipeCategoryUseCase.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/GetRecipePreviewUseCase.kt
Labels: :sparkles: feature

#89 ♻️ [REFACTOR] toggle preferences ui logic
  app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/RecipeNavGraph.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeCard.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeList.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListContent.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipeMenuScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipePreviewByOwner.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipeScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/viewmodel/RecipeListViewModel.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/ToggleLikeListUseCase.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/ToggleLikeUseCase.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/ToggleScrapListUseCase.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/ToggleScrapUseCase.kt
  app/src/main/java/com/zipdabang/zipdabang_android/ui/component/GroupHeader.kt
Labels: :recycle: refactor

#93 :sparkles: [FEAT] Remember-Me on Splash Screen Business Logic
  app/src/main/java/com/zipdabang/zipdabang_android/common/ResponseCode.kt
  app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/RootNavGraph.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/use_case/GetRecipeDetailUseCase.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/viewmodel/RecipeListViewModel.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/viewmodel/RecipeMainViewModel.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/splash/SplashModule.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/splash/SplashViewModel.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/splash/data/AutoLoginDto.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/splash/data/AutoLoginRepositoryImpl.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/splash/data/NewTokenDto.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/splash/data/NewTokens.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/splash/data/RefreshTokenQuery.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/splash/di/SplashModule.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/splash/domain/AutoLoginApi.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/splash/domain/AutoLoginRepository.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/splash/ui/CheckAccessTokenState.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/splash/ui/NewTokenState.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/splash/ui/SplashScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/splash/ui/SplashViewModel.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/splash/use_case/CheckAccessTokenUseCase.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/splash/use_case/GetNewTokenUseCase.kt
  app/src/main/java/com/zipdabang/zipdabang_android/ui/component/GroupHeader.kt
Labels: :sparkles: feature

#103 ✨ [FEAT] 레시피 상세화면 레시피 조회 및 댓글 작성, 조회
  app/src/main/java/com/zipdabang/zipdabang_android/common/Constants.kt
  app/src/main/java/com/zipdabang/zipdabang_android/common/TabItem.kt
  app/src/main/java/com/zipdabang/zipdabang_android/core/AppModule.kt
  app/src/main/java/com/zipdabang/zipdabang_android/core/Paging3Database.kt
  app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/RecipeNavGraph.kt
  app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/SharedNavGraph.kt
  app/src/main/java/com/zipdabang/zipdabang_android/core/remotekey/dao/RemoteKeyDao.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/data/RecipeCommentRepositoryImpl.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/data/local/RecipeCommentDao.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/data/local/RecipeCommentEntity.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/data/remote/PostCommentContent.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/data/remote/PostCommentDto.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/data/remote/PostCommentResult.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/data/remote/RecipeComment.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/data/remote/RecipeCommentDto.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/data/remote/RecipeCommentResult.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/domain/CommentMgtResult.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/domain/PostResult.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/domain/RecipeCommentListMediator.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/domain/RecipeCommentRepository.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/ui/CommentListContent.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/ui/PostCommentState.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/ui/RecipeCommentPage.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/ui/RecipeCommentState.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/ui/RecipeCommentViewModel.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/ui/components/CommentItem.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/ui/components/CommentSubmit.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/ui/components/CommentSubmitButton.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/ui/components/CommentTextField.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/use_case/InsertCommentItemUseCase.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/use_case/PostCommentUseCase.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/comment/util/RecipeCommentMapper.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/ui/DeviceScreenSize.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/ui/RecipeDetailScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/ui/RecipeDetailViewModel.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/ui/RecipeInfoPage.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/use_case/GetRecipeDetailUseCase.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/data/RecipeApi.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/di/RecipeModule.kt
  app/src/main/java/com/zipdabang/zipdabang_android/ui/component/AppBar.kt
  app/src/main/java/com/zipdabang/zipdabang_android/ui/component/Pager.kt
  app/src/main/res/values/strings.xml
Labels: :sparkles: feature

#108 ⚡♻️💄 [FIX] User Preferences 관련 사용자 경험 개선을 위한 UI 로직 수정
  app/src/main/java/com/zipdabang/zipdabang_android/common/Exception.kt
  app/src/main/java/com/zipdabang/zipdabang_android/core/AppModule.kt
  app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/SharedNavGraph.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/common/DeviceScreenSize.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/data/RecipeInfo.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/ui/RecipeDetailPreference.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/ui/RecipeDetailScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/ui/RecipeDetailViewModel.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeCard.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListContent.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipeCategory.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipeMenuScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipePreview.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipePreviewByOwner.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipeScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/viewmodel/RecipeListViewModel.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/viewmodel/RecipeMainViewModel.kt
  app/src/main/java/com/zipdabang/zipdabang_android/ui/component/AppBar.kt
  app/src/main/java/com/zipdabang/zipdabang_android/ui/component/Pager.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, :recycle: refactor, :lipstick: styling

#127 ♻️🐛 [FIX] 로그아웃 api 매개변수 수정
  app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/MyApi.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/repository/MyRepositoryImpl.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/my/di/MyModule.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/my/domain/repository/MyRepository.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/viewmodel/MyViewModel.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/my/use_case/SignOutUseCase.kt
Labels: :recycle: refactor, :bug: bug

#131 📝 [DOCS] README.md 파일 주요 사항 작성
  README.md
Labels: :memo: docs

#138 ✨ [FEAT] FCM Notification 전송 및 클릭 이벤트 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/zipdabang/zipdabang_android/common/AnimatedShimmer.kt
  app/src/main/java/com/zipdabang/zipdabang_android/core/messaging/FirebaseCloudMessagingService.kt
  app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/HomeNavGraph.kt
  app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/MainNavGraph.kt
  app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/RootNavGraph.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/home/ui/HomeScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/main/FCMData.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/main/MainActivity.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/main/MainScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/splash/data/NewTokenDto.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/splash/ui/SplashScreen.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/splash/ui/SplashViewModel.kt
  app/src/main/java/com/zipdabang/zipdabang_android/module/splash/use_case/CheckAccessTokenUseCase.kt
  app/src/main/java/com/zipdabang/zipdabang_android/ui/component/Button.kt
Labels: :sparkles: feature
